services:
  backend:
    build: .
    container_name: estore-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

# To use H2 in server mode (shared or persistent DB), uncomment the following service
# and update SPRING_DATASOURCE_URL in the backend service to:
#   jdbc:h2:tcp://h2:1521/mem:testdb
#
# h2:
#   image: oscarfonts/h2
#   container_name: h2
#   ports:
#     - "1521:1521"
#     - "81:81"
#   environment:
#     H2_OPTIONS: "-ifNotExists"
#   command: -tcp -tcpAllowOthers -web -webAllowOthers -tcpPort 1521 -webPort 81 